#!/usr/bin/env sh
set -eu

if ! git rev-parse --git-dir >/dev/null 2>&1; then
  exit 0
fi

if git status --short | grep --quiet '^MM'; then
  printf '%s\n' "ERROR: Some staged files have unstaged changes" >&2
  exit 1;
fi

bun run lint-staged

git update-index --again
